const PRODUCTS = [
 {id:1,name:'Essential Black T-Shirt',category:'T-Shirts',style:'Casual',price:120,old:150,rating:4.5,discount:20,new:true,popular:true,images:['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85']},
 {id:2,name:'Skinny Fit Jeans',category:'Jeans',style:'Casual',price:240,old:260,rating:3.5,discount:20,new:true,popular:true,images:['https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=85']},
 {id:3,name:'Checkered Shirt',category:'Shirts',style:'Casual',price:180,old:null,rating:4.5,discount:0,new:true,popular:true,images:['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1596755389378-c31d21fd1273?auto=format&fit=crop&w=900&q=85']},
 {id:4,name:'Sleeve Striped T-Shirt',category:'T-Shirts',style:'Casual',price:130,old:160,rating:4.5,discount:30,new:true,popular:true,images:['https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1503341504253-dff4815485f1?auto=format&fit=crop&w=900&q=85']},
 {id:5,name:'Vertical Striped Shirt',category:'Shirts',style:'Formal',price:212,old:232,rating:5,discount:20,new:false,popular:true,images:['https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?auto=format&fit=crop&w=900&q=85']},
 {id:6,name:'Courage Graphic T-Shirt',category:'T-Shirts',style:'Casual',price:145,old:null,rating:4,ratingCount:0,discount:0,new:false,popular:true,images:['https://images.unsplash.com/photo-1583743814966-8936f37f4678?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1583743814966-8936f37f4678?auto=format&fit=crop&w=900&q=85']},
 {id:7,name:'Loose Fit Bermuda Shorts',category:'Jeans',style:'Casual',price:80,old:null,rating:3,ratingCount:0,discount:0,new:false,popular:true,images:['https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=85']},
 {id:8,name:'Faded Skinny Jeans',category:'Jeans',style:'Casual',price:210,old:250,rating:4.5,discount:20,new:false,popular:true,images:['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=85']},
 {id:9,name:'Minimal Bomber Jacket',category:'Jackets',style:'Party',price:275,old:320,rating:4.5,discount:15,new:true,popular:false,images:['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85']},
 {id:10,name:'Classic Formal Blazer',category:'Jackets',style:'Formal',price:299,old:350,rating:5,discount:15,new:false,popular:false,images:['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=900&q=85']},
 {id:11,name:'Performance Training Tee',category:'Activewear',style:'Gym',price:110,old:null,rating:4.5,discount:0,new:true,popular:false,images:['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=900&q=85']},
 {id:12,name:'Relaxed Everyday Hoodie',category:'Jackets',style:'Casual',price:195,old:220,rating:4.5,discount:10,new:true,popular:false,images:['https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85','https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85']}
];
const REVIEWS=[['Sarah M.','“I’m blown away by the quality and style of the clothes I received from NOVA. From casual wear to elegant pieces, every price feels right.”'],['Alex K.','“Finding clothes that align with my personal style used to be a challenge until I discovered NOVA. The range of options is truly impressive.”'],['James L.','“As someone who’s always on the lookout for unique fashion pieces, I’m thrilled to have stumbled upon NOVA.”'],['Maya P.','“The details, fit and overall shopping experience have been excellent. I’ll definitely be back.”']];
function money(v){return '$'+v.toFixed(0)}
function stars(r){return '★'.repeat(Math.floor(r)) + (r%1 ? '★' : '') + `<small>${r.toFixed(1)}/5</small>`}
function productCard(p){return `<article class="product-card"><a href="product.html?id=${p.id}" class="product-image"><img src="${p.images[0]}" alt="${p.name}" loading="lazy"></a><a class="product-name" href="product.html?id=${p.id}">${p.name}</a><div class="rating">${stars(p.rating)}</div><div class="price">${money(p.price)} ${p.old?`<del>${money(p.old)}</del><span class="sale">-${p.discount}%</span>`:''}</div></article>`}
function getCart(){try{return JSON.parse(localStorage.getItem('nova-cart')||'[]')}catch{return []}}
function setCart(c){localStorage.setItem('nova-cart',JSON.stringify(c))}
function addToCart(id,qty=1,size='M',color='Black'){const cart=getCart();const item=cart.find(x=>x.id===id&&x.size===size&&x.color===color);if(item)item.qty+=qty;else cart.push({id,qty,size,color});setCart(cart);toast('Added to cart');}
function toast(msg){const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2200)}
function initCommon(){document.querySelectorAll('.promo-close').forEach(b=>b.onclick=()=>b.parentElement.remove());const ham=document.getElementById('hamburger'), menu=document.getElementById('mobileMenu');if(ham)ham.onclick=()=>{ham.classList.toggle('open');menu.classList.toggle('open')};const search=document.getElementById('globalSearch');if(search)search.addEventListener('keydown',e=>{if(e.key==='Enter'&&search.value.trim())location.href='shop.html?q='+encodeURIComponent(search.value.trim())});document.querySelectorAll('#newsletterForm').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();toast('Thanks! You are subscribed.');f.reset()}));}
function initHome(){const n=document.getElementById('newArrivals'),t=document.getElementById('topSelling'),r=document.getElementById('reviews');if(!n)return;n.innerHTML=PRODUCTS.filter(p=>p.new).slice(0,4).map(productCard).join('');t.innerHTML=PRODUCTS.filter(p=>p.popular).slice(0,4).map(productCard).join('');let start=0;function renderReviews(){r.innerHTML=REVIEWS.slice(start,start+3).map(x=>`<article class="review"><div class="rating">★★★★★ <small>5.0/5</small></div><h3>${x[0]} <b>✓</b></h3><p>${x[1]}</p></article>`).join('')}renderReviews();document.getElementById('reviewNext')?.addEventListener('click',()=>{start=(start+1)%2;renderReviews()});document.getElementById('reviewPrev')?.addEventListener('click',()=>{start=(start+1)%2;renderReviews()})}
function initShop(){const grid=document.getElementById('shopProducts');if(!grid)return;const params=new URLSearchParams(location.search);const q=(params.get('q')||'').toLowerCase();let currentPage=1,perPage=9;let data=[...PRODUCTS];if(q)data=data.filter(p=>(p.name+p.category+p.style).toLowerCase().includes(q));if(params.get('style'))data=data.filter(p=>p.style.toLowerCase()===params.get('style').toLowerCase());if(params.get('sort')==='new')data.sort((a,b)=>b.new-a.new);if(params.get('sort')==='popular')data.sort((a,b)=>b.popular-a.popular);if(params.get('sort')==='sale')data=data.filter(p=>p.discount>0);document.getElementById('shopTitle').textContent=params.get('style')?params.get('style').replace(/^./,c=>c.toUpperCase()):q?'Search results':params.get('sort')==='sale'?'On Sale':'Shop';const render=()=>{const start=(currentPage-1)*perPage;grid.innerHTML=data.slice(start,start+perPage).map(productCard).join('');document.getElementById('resultCount').textContent=`Showing ${Math.min(start+1,data.length)}-${Math.min(start+perPage,data.length)} of ${data.length} Products`;const pages=Math.ceil(data.length/perPage);document.getElementById('pagination').innerHTML=Array.from({length:pages},(_,i)=>`<button class="${i+1===currentPage?'active':''}" data-page="${i+1}">${i+1}</button>`).join('');document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{currentPage=+b.dataset.page;render();window.scrollTo({top:0,behavior:'smooth'})})};document.getElementById('sortSelect').onchange=e=>{const v=e.target.value;if(v==='new')data.sort((a,b)=>b.new-a.new);if(v==='price-low')data.sort((a,b)=>a.price-b.price);if(v==='price-high')data.sort((a,b)=>b.price-a.price);if(v==='popular')data.sort((a,b)=>b.popular-a.popular);currentPage=1;render()};document.getElementById('applyFilters').onclick=()=>{const cats=[...document.querySelectorAll('.filters input[type=checkbox]:checked')].map(x=>x.value);const min=+document.getElementById('minPrice').value||0,max=+document.getElementById('maxPrice').value||Infinity;data=PRODUCTS.filter(p=>(!cats.length||cats.includes(p.category)||cats.includes(p.style))&&p.price>=min&&p.price<=max&&(!q||(p.name+p.category+p.style).toLowerCase().includes(q)));currentPage=1;render()};document.getElementById('clearFilters').onclick=()=>location.href='shop.html';render()}
initCommon();initHome();initShop();
